### ISSUE TITLE
Comparison to other libraries?

### ISSUE THREAD

**Issue by adam-hartshorne** [pnkraemer/matfree#160]
I am just wondering if you could explain the similarities / difference between this library and for instance CoLA, which also offers the likes of Hutchinson, Arnoldi, Lanczos, etc ?

**Comment by pnkraemer** [comment]
Similarities: 

Both seem to do something with linear algebra, both avoid materialising dense matrices, and both build on JAX (CoLa also seems to support Pytorch).

Differences: 

CoLa seems to operate on LinearOperator-style classes, which is helpful if you work with many structured matrices but requires maintaining code that dispatches between methods depending on the operator class. (If I misunderstood something regarding CoLa, please correct me.) 

Matfree operates exclusively on the level of matrix-vector product callables, therefore it does not come with object-oriented code like "Diag+Diag=Diag" but it is straightforward to apply to, say, Pytree-valued Jacobian-vector-products. You can consider matfree as a lightweight extension of jax.scipy.sparse.linalg.

**Comment by pnkraemer** [comment]
I will close this issue as it seems to be complete. 

If you have a follow-up question @adam-hartshorne, please feel free to reopen with a further comment! :)
