### ISSUE TITLE
CUDA backend

### ISSUE THREAD

**Issue by qiyang-ustc** [pnkraemer/matfree#225]
I made a lot of efforts in related topics, I want to confirm the most difficult part of the transfering backend from CPU to GPU. For eigs, I guess the problem is there is no native implementation of eig implementation GPU backend in JAX?

What I did in jaxeigs is to use `pure_callback`. In general, the eigensolver in the Krylov space is a CPU-friendly task.

**Comment by pnkraemer** [comment]
Thanks for reaching out!

Sorry, but I am not sure I understand your point. Could you perhaps specify which issue you've encountered?

**Comment by qiyang-ustc** [comment]
I am just wondering how matfree implement eigs on GPU(matrix free-eigensolver). It has been discussed for a long time. see, https://github.com/jax-ml/jax/issues/3112.
I checked the relative file in matfree but found no content? https://github.com/pnkraemer/matfree/blob/main/matfree/eig.py

**Comment by pnkraemer** [comment]
Thanks for elaborating @qiyang-ustc! 

Currently, there is no dedicated eigenvalue solver. There is a partial SVD, and partial eigenvalue solvers are planned for the future (but not with high priority unless someone explicitly asks for it).

As for CUDA, matfree currently does not distinguish between CPU and GPU code and leaves all such implementations to the JAX functions that are called. Does that help?

**Comment by pnkraemer** [comment]
> So, now one can simply combine Arnoldi decomposition(in matfree) with lax.linalg.eig to obtain an JITable, ADable, Krylov eigensolver in JAX!

Yes, this is what I had in mind for building eigendecompositions :) It's also how the partial SVD is currently implemented.

Do you think we should close this issue then? We can open a separate one for implementing a partial eigenvalue decomposition in matfree.eig if you want. What do you think?

**Comment by qiyang-ustc** [comment]
I completely agree with you. Thank you, looking forward it!

**Comment by pnkraemer** [comment]
The development of eig(h)_partial is tracked in #227. I'll close the present issue then; again, thanks for reaching out!

**Comment by pnkraemer** [comment]
FYI, with #234 implements partial eigendecompositions by combining Arnoldi with linalg.eig. After the next release (likely in a few days), matfree will support this. Let me know if this works for you!
